% addpath('bhv-ephys');

combdatlist = {...
    './vplt-dim/Apr22/data.mat', ...
    './vplt-dim/Apr24/data.mat', ...
    './vplt-dim/Apr27/data.mat', ...
    './vplt-dim/Apr29/data.mat', ...
    './vplt-dim/Apr30/data.mat', ...
    './vplt-dim/May1/data.mat', ...
    {}, ...
    './vplt-dim/May7/data.mat', ...
    './vplt-dim/May8/data1.mat', ...
    './vplt-dim/May8/data2.mat', ...
    './vplt-dim/May12/data.mat', ...
    {}, ...
    './vplt-dim/May13/data.mat', ...
    {}, ...
    './vplt-dim/May14/data.mat', ...
    {}, ...
    {}, ...
    './vplt-dim/May15/data.mat', ...
    };
imgloglist = {...
    './vplt-dim/Apr22/dim_pref_look_nolever-bootsy-04-22-2015_imglog.txt', ...
    './vplt-dim/Apr24/dim_pref_look_nolever-bootsy-04-24-2015_imglog.txt', ...
    './vplt-dim/Apr27/dim_pref_look_nolever-bootsy-04-27-2015_imglog.txt', ...
    './vplt-dim/Apr29/dim_pref_look_nolever-bootsy-04-29-2015_imglog.txt', ...
    './vplt-dim/Apr30/dim_pref_look_nolever-bootsy-04-30-2015_imglog.txt', ...
    './vplt-dim/May1/dim_pref_look_nolever-bootsy-05-01-2015_imglog.txt', ...
    './vplt-dim/May4/dim_pref_look_nolever-bootsy-05-04-2015_imglog.txt', ...
    './vplt-dim/May7/dim_pref_look_nolever-bootsy-05-07-2015_imglog.txt', ...
    './vplt-dim/May8/dim_pref_look_nolever-bootsy-05-08-2015_imglog_file1.txt', ...
    './vplt-dim/May8/dim_pref_look_nolever-bootsy-05-08-2015_file2_imglog.txt', ...
    './vplt-dim/May12/dim_pref_look_nolever-bootsy-05-12-2015_imglog.txt', ...
    './vplt-dim/May13/dim_pref_look_nolever-bootsy-05-13-2015_test_imglog.txt', ...
    './vplt-dim/May13/dim_pref_look_nolever-bootsy-05-13-2015_imglog.txt', ...
    './vplt-dim/May14/dim_pref_look_nolever-bootsy-05-14-2015_test_imglog.txt', ...
    './vplt-dim/May14/dim_pref_look_nolever-bootsy-05-14-2015_imglog.txt', ...
    './vplt-dim/May15/dim_pref_look_nolever-bootsy-05-15-2015_test_imglog.txt', ...
    './vplt-dim/May15/dim_pref_look_nolever-bootsy-05-15-2015_imglog_file1.txt', ...
    './vplt-dim/May15/dim_pref_look_nolever-bootsy-05-15-2015_imglog.txt', ...
    };
savename = 'bootsy-early-bhvit.mat';

dats = loadAllData(combdatlist);
augdats = augmentBHV(dats, imgloglist);
for i = 1:length(augdats)
    if ~isempty(augdats{i})
        augdats{i}.BHV.DataNum = i;
        x = create_trial_structure_dimming_and_vpl(augdats{i}, {}, true, {});
        if i == 1
            superx = x';
        else
            superx = cat(1, superx, x');
        end
        x = x';
        save(sprintf('bootsy-bhvit-run-rf%i.mat', i), 'x');
    end
end

save(savename, 'superx', '-v7.3');
