% marshal data

bhvpaths = {...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-06-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-07-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-08-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-08-2015_file2.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-11-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-12-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-12-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-13-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-13-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-14-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-14-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-15-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-15-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-18-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-18-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015(01).mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015_rec.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-22-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-22-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015_afterrec.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015_file2.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-28-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-28-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015_file2.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-01-2015_test.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-01-2015.mat', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-02-2015_train.mat' ...
    };

imgpaths = {...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-06-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-07-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-08-2015_imglog_file1.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-08-2015_file2_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-11-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-12-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-12-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-13-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-13-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-14-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-14-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-15-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-15-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-18-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-18-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-19-2015(01)_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-20-2015_rec_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-22-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-22-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-26-2015_afterrec_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-27-2015_file2_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-28-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-28-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-05-29-2015_file2_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-01-2015_test_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-01-2015_imglog.txt', ...
    '../../../experiments/pref_looking/tomerge/dim_pref_look_nolever-bootsy-06-02-2015_train_imglog.txt' ...
    };

makeEvolPlot(bhvpaths, imgpaths);

