imgpaths = {...
    'cross-session/dim_pref_look_nolever-bootsy-10-07-2015_imglog.txt', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-08-2015_imglog.txt', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-09-2015_imglog.txt', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-10-2015_imglog.txt', ...
    };
bhvpaths = {...
    'cross-session/dim_pref_look_nolever-bootsy-10-07-2015.mat', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-08-2015.mat', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-09-2015.mat', ...
    'cross-session/dim_pref_look_nolever-bootsy-10-10-2015.mat', ...
    };

% imgpaths = {...
%     'singlesession-10-01-15/dim_pref_look_nolever-bootsy-10-01-2015_imglog.txt', ...
%     };
% 
% bhvpaths = {...
%     'singlesession-10-01-15/dim_pref_look_nolever-bootsy-10-01-2015.mat', ...
%     };

params.reductionFactor = 3;
params.titleText = 'short scale';
params.tottime = 4000;
params.bigWindowSize = 1000;
params.incond = 12; % IF
params.nicond = 13; % FI
bars = 5;
entries = 3;

allbws = zeros(length(imgpaths), bars, entries);
for i = 1:length(imgpaths)
    bw = makeEvolPlot(bhvpaths(i), imgpaths(i), params);
    allbws(i, :, :) = bw;
end


