% addpath('bhv-ephys');

combdatlist = {...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/May7/data.mat', ...
    {}, ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/May12/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May13/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May14/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May15/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May18/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May19/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May22/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/May26/data.mat', ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/Jun1/data.mat', ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/Jun3/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jun4/data.mat', ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/Jun10/data.mat', ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/Jun15/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jun18/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jun19/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jun22/data.mat', ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    '~/data/vplt-dim-resort/Jul10/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jul14/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jul15/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jul16/data.mat', ...
    {}, ...
    '~/data/vplt-dim-resort/Jul17/data.mat', ...
    };

imgloglist = {...
    '~/data/vplt-dim-resort/Apr22/dim_pref_look_nolever-bootsy-04-22-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Apr23/dim_pref_look_nolever-bootsy-04-23-2015(03)_imglog.txt', ...
    '~/data/vplt-dim-resort/Apr24/dim_pref_look_nolever-bootsy-04-24-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Apr27/dim_pref_look_nolever-bootsy-04-27-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Apr28/dim_pref_look_nolever-bootsy-04-28-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Apr29/dim_pref_look_nolever-bootsy-04-29-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May1/dim_pref_look_nolever-bootsy-05-01-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May4/dim_pref_look_nolever-bootsy-05-04-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May5/dim_pref_look_nolever-bootsy-05-05-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May6/dim_pref_look_nolever-bootsy-05-06-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May7/dim_pref_look_nolever-bootsy-05-07-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May8/dim_pref_look_nolever-bootsy-05-08-2015_imglog_file1.txt', ...
    '~/data/vplt-dim-resort/May8/dim_pref_look_nolever-bootsy-05-08-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/May12/dim_pref_look_nolever-bootsy-05-12-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May12/dim_pref_look_nolever-bootsy-05-12-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May13/dim_pref_look_nolever-bootsy-05-13-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May13/dim_pref_look_nolever-bootsy-05-13-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May14/dim_pref_look_nolever-bootsy-05-14-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May14/dim_pref_look_nolever-bootsy-05-14-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May15/dim_pref_look_nolever-bootsy-05-15-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May15/dim_pref_look_nolever-bootsy-05-15-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May18/dim_pref_look_nolever-bootsy-05-18-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May18/dim_pref_look_nolever-bootsy-05-18-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May19/dim_pref_look_nolever-bootsy-05-19-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May19/dim_pref_look_nolever-bootsy-05-19-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May22/dim_pref_look_nolever-bootsy-05-22-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May22/dim_pref_look_nolever-bootsy-05-22-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May26/dim_pref_look_nolever-bootsy-05-26-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/May26/dim_pref_look_nolever-bootsy-05-26-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/May26/dim_pref_look_nolever-bootsy-05-26-2015_afterrec_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun1/dim_pref_look_nolever-bootsy-06-01-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun1/dim_pref_look_nolever-bootsy-06-01-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun2/dim_pref_look_nolever-bootsy-06-02-2015_train_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun3/dim_pref_look_nolever-bootsy-06-03-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun3/dim_pref_look_nolever-bootsy-06-03-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun4/dim_pref_look_nolever-bootsy-06-04-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun4/dim_pref_look_nolever-bootsy-06-04-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun5/dim_pref_look_nolever-bootsy-06-05-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun5/dim_pref_look_nolever-bootsy-06-05-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun8/dim_pref_look_nolever-bootsy-06-08-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun9/dim_pref_look_nolever-bootsy-06-09-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun10/dim_pref_look_nolever-bootsy-06-10-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun10/dim_pref_look_nolever-bootsy-06-10-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun11/dim_pref_look_nolever-bootsy-06-11-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun11/dim_pref_look_nolever-bootsy-06-11-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun11/dim_pref_look_nolever-bootsy-06-11-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun12/dim_pref_look_nolever-bootsy-06-12-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun12/dim_pref_look_nolever-bootsy-06-12-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun15/dim_pref_look_nolever-bootsy-06-15-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun15/dim_pref_look_nolever-bootsy-06-15-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun18/dim_pref_look_nolever-bootsy-06-18-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun18/dim_pref_look_nolever-bootsy-06-18-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun19/dim_pref_look_nolever-bootsy-06-19-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun19/dim_pref_look_nolever-bootsy-06-19-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun22/dim_pref_look_nolever-bootsy-06-22-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun22/dim_pref_look_nolever-bootsy-06-22-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun23/dim_pref_look_nolever-bootsy-06-23-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun23/dim_pref_look_nolever-bootsy-06-23-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun24/dim_pref_look_nolever-bootsy-06-24-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun24/dim_pref_look_nolever-bootsy-06-24-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun24/dim_pref_look_nolever-bootsy-06-24-2015_location2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun24/dim_pref_look_nolever-bootsy-06-24-2015_location2_rec_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun30/dim_pref_look_nolever-bootsy-06-30-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun30/dim_pref_look_nolever-bootsy-06-30-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun30/dim_pref_look_nolever-bootsy-06-30-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jun30/dim_pref_look_nolever-bootsy-06-30-2015_file3_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul1/dim_pref_look_nolever-bootsy-07-01-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul1/dim_pref_look_nolever-bootsy-07-01-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul2/dim_pref_look_nolever-bootsy-07-02-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul2/dim_pref_look_nolever-bootsy-07-02-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul3/dim_pref_look_nolever-bootsy-07-03-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul3/dim_pref_look_nolever-bootsy-07-03-2015_test2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul3/dim_pref_look_nolever-bootsy-07-03-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul3/dim_pref_look_nolever-bootsy-07-03-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul6/dim_pref_look_nolever-bootsy-07-06-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul6/dim_pref_look_nolever-bootsy-07-06-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul6/dim_pref_look_nolever-bootsy-07-06-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul6/dim_pref_look_nolever-bootsy-07-06-2015_file3_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul6/dim_pref_look_nolever-bootsy-07-06-2015_file4_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul7/dim_pref_look_nolever-bootsy-07-07-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul7/dim_pref_look_nolever-bootsy-07-07-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul7/dim_pref_look_nolever-bootsy-07-07-2015(01)_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul8/dim_pref_look_nolever-bootsy-07-08-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul8/dim_pref_look_nolever-bootsy-07-08-2015_test2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul8/dim_pref_look_nolever-bootsy-07-08-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul8/dim_pref_look_nolever-bootsy-07-08-2015_file2_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul9/dim_pref_look_nolever-bootsy-07-09-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul9/dim_pref_look_nolever-bootsy-07-09-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul10/dim_pref_look_nolever-bootsy-07-10-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul10/dim_pref_look_nolever-bootsy-07-10-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul14/dim_pref_look_nolever-bootsy-07-14-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul14/dim_pref_look_nolever-bootsy-07-14-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul15/dim_pref_look_nolever-bootsy-07-15-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul15/dim_pref_look_nolever-bootsy-07-15-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul16/dim_pref_look_nolever-bootsy-07-16-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul16/dim_pref_look_nolever-bootsy-07-16-2015_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul17/dim_pref_look_nolever-bootsy-07-17-2015_test_imglog.txt', ...
    '~/data/vplt-dim-resort/Jul17/dim_pref_look_nolever-bootsy-07-17-2015_imglog.txt' ...
    };

savename = 'bootsy-early-bhvit.mat';

dats = loadAllData(combdatlist);
augdats = augmentBHV(dats, imgloglist);
j = 0;
for i = 1:length(augdats)
    if ~isempty(augdats{i})
        j = j + 1;
        augdats{i}.BHV.DataNum = i;
        x = create_trial_structure_dimming_and_vpl(augdats{i}, {}, true, {});
        if j == 1
            superx = x';
        else
            superx = cat(1, superx, x');
        end
        x = x';
        save(sprintf('bootsy-bhvit-rs-run%i.mat', i), 'x');
    end
end

save(savename, 'superx', '-v7.3');
